[package]
name = "onepub_program"
version = "0.1.0"
edition = "2018"
authors = ["azuldev azuldevgames@gmail.com"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.9"
solana-program = "1.14.18"
sha2 = "0.9.5"